@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes EventDeleteCommand;
:Model loads filtered event lists;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([event index out of range])
    :Display index out of
    range error message;
    stop
else ([else])
    :Delete the event from the list;
    :Update the event storage;
    :Return CommandResult with success message;
    stop
endif
@enduml
