@startuml
!include styleFields.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeIconSize 0

package EVENT <<Rectangle>>{
Class Event
Class Role {
  + roleName : String
  + currentQuantity : int
  + requiredQuantity : int
  + addRoleManpower() : Role
  + decreaseRoleManpower() : Role
  + hasEnoughManpower() : boolean
}
Class Material {
  + materialName : String
  + currentQuantity : int
  + requiredQuantity : int
  + addItems(int addedQuantity) : Material
  + hasEnoughItems() : boolean
}
Class I #FFFFFF
note right of Event : All other fields\nof Event hidden
}

hide Event members

Event *-down-> "1..*" Role
Event *-down-> "1..*" Material
@enduml
