@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "Volunteer Storage" #F4F6F6{
Class "<<interface>>\nVolunteerStorage" as VolunteerStorage
Class JsonVolunteerStorage
Class JsonSerializableVolunteerStorage
Class JsonAdaptedVolunteer
Class JsonAdaptedSkill
Class JsonAdaptedEventName
}

package "Event Storage" #F4F6F6{
Class "<<interface>>\nEventStorage" as EventStorage
Class JsonEventStorage
Class JsonSerializableEventStorage
Class JsonAdaptedEvent
Class JsonAdaptedMaterial
Class JsonAdaptedRole
Class JsonAdaptedName
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -left-> "1" UserPrefsStorage
StorageManager -down-> "1" VolunteerStorage
StorageManager -right-> "1" EventStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> EventStorage
Storage -down-|> VolunteerStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonVolunteerStorage .up.|> VolunteerStorage
JsonVolunteerStorage ..> JsonSerializableVolunteerStorage
JsonSerializableVolunteerStorage --> "*" JsonAdaptedVolunteer
JsonAdaptedVolunteer --> "*" JsonAdaptedSkill
JsonAdaptedVolunteer --> "*" JsonAdaptedEventName

JsonEventStorage .up.|> EventStorage
JsonEventStorage ..> JsonSerializableEventStorage
JsonSerializableEventStorage --> "*" JsonAdaptedEvent
JsonAdaptedEvent --> "*" JsonAdaptedRole
JsonAdaptedEvent --> "*" JsonAdaptedMaterial
JsonAdaptedEvent --> "*" JsonAdaptedName

@enduml
