@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "vdelete 5"

package States <<rectangle>> {
    class State1 as "<u>v0:VolunteerStorage</u>"
    class State2 as "<u>v1:VolunteerStorage</u>"
    class State3 as "<u>v2:VolunteerStorage</u>"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

hide State3

class Pointer as "Current State" #FFFFFF

Pointer -up-> State2
@end
